(ns clojure-elisp.jvm-names
  "What an unqualified symbol means inside a syntax-quote, fixed once.

   LispReader resolves `foo against the ns-map of *ns*: a var referred from
   clojure.core becomes clojure.core/foo, an imported class its full name, and
   anything else *ns*/foo. Each host's ns-map differs: ClojureWasm has no
   binding, test, ns, load or sync var and imports no java.lang classes, and
   Babashka's user ns refers clojure.repl/doc, clojure.pprint/pp and more. So
   the same defmacro compiled to different Elisp on each host.

   The compiler resolves against this snapshot instead: the clojure.core vars
   and java.lang classes a fresh JVM user namespace refers, taken from Clojure
   1.12.4 (the version deps.edn pins). The JVM's own output is unchanged for a
   fresh process, and every host now emits it.

   Regenerate with the JVM: sort the keys of (ns-map (the-ns 'user)) whose
   value is a clojure.core var, and the class entries with their names.
   Vectors, not literal sets and maps: `cljw build` cannot serialize
   hash-backed constants.")

(def core-vars
  "Names of the clojure.core vars a fresh JVM user namespace refers."
  (set
   ["*" "*'" "*1" "*2" "*3" "*agent*"
    "*allow-unresolved-vars*" "*assert*" "*clojure-version*" "*command-line-args*" "*compile-files*" "*compile-path*"
    "*compiler-options*" "*data-readers*" "*default-data-reader-fn*" "*e" "*err*" "*file*"
    "*flush-on-newline*" "*fn-loader*" "*in*" "*math-context*" "*ns*" "*out*"
    "*print-dup*" "*print-length*" "*print-level*" "*print-meta*" "*print-namespace-maps*" "*print-readably*"
    "*read-eval*" "*reader-resolver*" "*repl*" "*source-path*" "*suppress-read*" "*unchecked-math*"
    "*use-context-classloader*" "*verbose-defrecords*" "*warn-on-reflection*" "+" "+'" "-"
    "-'" "->" "->>" "->ArrayChunk" "->Eduction" "->Vec"
    "->VecNode" "->VecSeq" "-cache-protocol-fn" "-reset-methods" ".." "/"
    "<" "<=" "=" "==" ">" ">="
    "EMPTY-NODE" "Inst" "NaN?" "PrintWriter-on" "StackTraceElement->vec" "Throwable->map"
    "abs" "accessor" "aclone" "add-classpath" "add-tap" "add-watch"
    "agent" "agent-error" "agent-errors" "aget" "alength" "alias"
    "all-ns" "alter" "alter-meta!" "alter-var-root" "amap" "ancestors"
    "and" "any?" "apply" "areduce" "array-map" "as->"
    "aset" "aset-boolean" "aset-byte" "aset-char" "aset-double" "aset-float"
    "aset-int" "aset-long" "aset-short" "assert" "assoc" "assoc!"
    "assoc-in" "associative?" "atom" "await" "await-for" "await1"
    "bases" "bean" "bigdec" "bigint" "biginteger" "binding"
    "bit-and" "bit-and-not" "bit-clear" "bit-flip" "bit-not" "bit-or"
    "bit-set" "bit-shift-left" "bit-shift-right" "bit-test" "bit-xor" "boolean"
    "boolean-array" "boolean?" "booleans" "bound-fn" "bound-fn*" "bound?"
    "bounded-count" "butlast" "byte" "byte-array" "bytes" "bytes?"
    "case" "cast" "cat" "char" "char-array" "char-escape-string"
    "char-name-string" "char?" "chars" "chunk" "chunk-append" "chunk-buffer"
    "chunk-cons" "chunk-first" "chunk-next" "chunk-rest" "chunked-seq?" "class"
    "class?" "clear-agent-errors" "clojure-version" "coll?" "comment" "commute"
    "comp" "comparator" "compare" "compare-and-set!" "compile" "complement"
    "completing" "concat" "cond" "cond->" "cond->>" "condp"
    "conj" "conj!" "cons" "constantly" "construct-proxy" "contains?"
    "count" "counted?" "create-ns" "create-struct" "cycle" "dec"
    "dec'" "decimal?" "declare" "dedupe" "default-data-readers" "definline"
    "definterface" "defmacro" "defmethod" "defmulti" "defn" "defn-"
    "defonce" "defprotocol" "defrecord" "defstruct" "deftype" "delay"
    "delay?" "deliver" "denominator" "deref" "derive" "descendants"
    "destructure" "disj" "disj!" "dissoc" "dissoc!" "distinct"
    "distinct?" "doall" "dorun" "doseq" "dosync" "dotimes"
    "doto" "double" "double-array" "double?" "doubles" "drop"
    "drop-last" "drop-while" "eduction" "empty" "empty?" "ensure"
    "ensure-reduced" "enumeration-seq" "error-handler" "error-mode" "eval" "even?"
    "every-pred" "every?" "ex-cause" "ex-data" "ex-info" "ex-message"
    "extend" "extend-protocol" "extend-type" "extenders" "extends?" "false?"
    "ffirst" "file-seq" "filter" "filterv" "find" "find-keyword"
    "find-ns" "find-protocol-impl" "find-protocol-method" "find-var" "first" "flatten"
    "float" "float-array" "float?" "floats" "flush" "fn"
    "fn?" "fnext" "fnil" "for" "force" "format"
    "frequencies" "future" "future-call" "future-cancel" "future-cancelled?" "future-done?"
    "future?" "gen-class" "gen-interface" "gensym" "get" "get-in"
    "get-method" "get-proxy-class" "get-thread-bindings" "get-validator" "group-by" "halt-when"
    "hash" "hash-combine" "hash-map" "hash-ordered-coll" "hash-set" "hash-unordered-coll"
    "ident?" "identical?" "identity" "if-let" "if-not" "if-some"
    "ifn?" "import" "in-ns" "inc" "inc'" "indexed?"
    "infinite?" "init-proxy" "inst-ms" "inst-ms*" "inst?" "instance?"
    "int" "int-array" "int?" "integer?" "interleave" "intern"
    "interpose" "into" "into-array" "ints" "io!" "isa?"
    "iterate" "iteration" "iterator-seq" "juxt" "keep" "keep-indexed"
    "key" "keys" "keyword" "keyword?" "last" "lazy-cat"
    "lazy-seq" "let" "letfn" "line-seq" "list" "list*"
    "list?" "load" "load-file" "load-reader" "load-string" "loaded-libs"
    "locking" "long" "long-array" "longs" "loop" "macroexpand"
    "macroexpand-1" "make-array" "make-hierarchy" "map" "map-entry?" "map-indexed"
    "map?" "mapcat" "mapv" "max" "max-key" "memfn"
    "memoize" "merge" "merge-with" "meta" "method-sig" "methods"
    "min" "min-key" "mix-collection-hash" "mod" "munge" "name"
    "namespace" "namespace-munge" "nat-int?" "neg-int?" "neg?" "newline"
    "next" "nfirst" "nil?" "nnext" "not" "not-any?"
    "not-empty" "not-every?" "not=" "ns" "ns-aliases" "ns-imports"
    "ns-interns" "ns-map" "ns-name" "ns-publics" "ns-refers" "ns-resolve"
    "ns-unalias" "ns-unmap" "nth" "nthnext" "nthrest" "num"
    "number?" "numerator" "object-array" "odd?" "or" "parents"
    "parse-boolean" "parse-double" "parse-long" "parse-uuid" "partial" "partition"
    "partition-all" "partition-by" "partitionv" "partitionv-all" "pcalls" "peek"
    "persistent!" "pmap" "pop" "pop!" "pop-thread-bindings" "pos-int?"
    "pos?" "pr" "pr-str" "prefer-method" "prefers" "primitives-classnames"
    "print" "print-ctor" "print-dup" "print-method" "print-simple" "print-str"
    "printf" "println" "println-str" "prn" "prn-str" "promise"
    "proxy" "proxy-call-with-super" "proxy-mappings" "proxy-name" "proxy-super" "push-thread-bindings"
    "pvalues" "qualified-ident?" "qualified-keyword?" "qualified-symbol?" "quot" "rand"
    "rand-int" "rand-nth" "random-sample" "random-uuid" "range" "ratio?"
    "rational?" "rationalize" "re-find" "re-groups" "re-matcher" "re-matches"
    "re-pattern" "re-seq" "read" "read+string" "read-line" "read-string"
    "reader-conditional" "reader-conditional?" "realized?" "record?" "reduce" "reduce-kv"
    "reduced" "reduced?" "reductions" "ref" "ref-history-count" "ref-max-history"
    "ref-min-history" "ref-set" "refer" "refer-clojure" "reify" "release-pending-sends"
    "rem" "remove" "remove-all-methods" "remove-method" "remove-ns" "remove-tap"
    "remove-watch" "repeat" "repeatedly" "replace" "replicate" "require"
    "requiring-resolve" "reset!" "reset-meta!" "reset-vals!" "resolve" "rest"
    "restart-agent" "resultset-seq" "reverse" "reversible?" "rseq" "rsubseq"
    "run!" "satisfies?" "second" "select-keys" "send" "send-off"
    "send-via" "seq" "seq-to-map-for-destructuring" "seq?" "seqable?" "seque"
    "sequence" "sequential?" "set" "set-agent-send-executor!" "set-agent-send-off-executor!" "set-error-handler!"
    "set-error-mode!" "set-validator!" "set?" "short" "short-array" "shorts"
    "shuffle" "shutdown-agents" "simple-ident?" "simple-keyword?" "simple-symbol?" "slurp"
    "some" "some->" "some->>" "some-fn" "some?" "sort"
    "sort-by" "sorted-map" "sorted-map-by" "sorted-set" "sorted-set-by" "sorted?"
    "special-symbol?" "spit" "split-at" "split-with" "splitv-at" "str"
    "stream-into!" "stream-reduce!" "stream-seq!" "stream-transduce!" "string?" "struct"
    "struct-map" "subs" "subseq" "subvec" "supers" "swap!"
    "swap-vals!" "symbol" "symbol?" "sync" "tagged-literal" "tagged-literal?"
    "take" "take-last" "take-nth" "take-while" "tap>" "test"
    "the-ns" "thread-bound?" "time" "to-array" "to-array-2d" "trampoline"
    "transduce" "transient" "tree-seq" "true?" "type" "unchecked-add"
    "unchecked-add-int" "unchecked-byte" "unchecked-char" "unchecked-dec" "unchecked-dec-int" "unchecked-divide-int"
    "unchecked-double" "unchecked-float" "unchecked-inc" "unchecked-inc-int" "unchecked-int" "unchecked-long"
    "unchecked-multiply" "unchecked-multiply-int" "unchecked-negate" "unchecked-negate-int" "unchecked-remainder-int" "unchecked-short"
    "unchecked-subtract" "unchecked-subtract-int" "underive" "unquote" "unquote-splicing" "unreduced"
    "unsigned-bit-shift-right" "update" "update-in" "update-keys" "update-proxy" "update-vals"
    "uri?" "use" "uuid?" "val" "vals" "var-get"
    "var-set" "var?" "vary-meta" "vec" "vector" "vector-of"
    "vector?" "volatile!" "volatile?" "vreset!" "vswap!" "when"
    "when-first" "when-let" "when-not" "when-some" "while" "with-bindings"
    "with-bindings*" "with-in-str" "with-loading-context" "with-local-vars" "with-meta" "with-open"
    "with-out-str" "with-precision" "with-redefs" "with-redefs-fn" "xml-seq" "zero?"
    "zipmap"]))

(def classes
  "Short name -> full name of the classes a fresh JVM user namespace imports."
  (into {}
        (map vec)
        (partition
         2
         ["AbstractMethodError" "java.lang.AbstractMethodError" "Appendable" "java.lang.Appendable"
          "ArithmeticException" "java.lang.ArithmeticException" "ArrayIndexOutOfBoundsException" "java.lang.ArrayIndexOutOfBoundsException"
          "ArrayStoreException" "java.lang.ArrayStoreException" "AssertionError" "java.lang.AssertionError"
          "BigDecimal" "java.math.BigDecimal" "BigInteger" "java.math.BigInteger"
          "Boolean" "java.lang.Boolean" "Byte" "java.lang.Byte"
          "Callable" "java.util.concurrent.Callable" "CharSequence" "java.lang.CharSequence"
          "Character" "java.lang.Character" "Class" "java.lang.Class"
          "ClassCastException" "java.lang.ClassCastException" "ClassCircularityError" "java.lang.ClassCircularityError"
          "ClassFormatError" "java.lang.ClassFormatError" "ClassLoader" "java.lang.ClassLoader"
          "ClassNotFoundException" "java.lang.ClassNotFoundException" "CloneNotSupportedException" "java.lang.CloneNotSupportedException"
          "Cloneable" "java.lang.Cloneable" "Comparable" "java.lang.Comparable"
          "Compiler" "clojure.lang.Compiler" "Deprecated" "java.lang.Deprecated"
          "Double" "java.lang.Double" "Enum" "java.lang.Enum"
          "EnumConstantNotPresentException" "java.lang.EnumConstantNotPresentException" "Error" "java.lang.Error"
          "Exception" "java.lang.Exception" "ExceptionInInitializerError" "java.lang.ExceptionInInitializerError"
          "Float" "java.lang.Float" "IllegalAccessError" "java.lang.IllegalAccessError"
          "IllegalAccessException" "java.lang.IllegalAccessException" "IllegalArgumentException" "java.lang.IllegalArgumentException"
          "IllegalMonitorStateException" "java.lang.IllegalMonitorStateException" "IllegalStateException" "java.lang.IllegalStateException"
          "IllegalThreadStateException" "java.lang.IllegalThreadStateException" "IncompatibleClassChangeError" "java.lang.IncompatibleClassChangeError"
          "IndexOutOfBoundsException" "java.lang.IndexOutOfBoundsException" "InheritableThreadLocal" "java.lang.InheritableThreadLocal"
          "InstantiationError" "java.lang.InstantiationError" "InstantiationException" "java.lang.InstantiationException"
          "Integer" "java.lang.Integer" "InternalError" "java.lang.InternalError"
          "InterruptedException" "java.lang.InterruptedException" "Iterable" "java.lang.Iterable"
          "LinkageError" "java.lang.LinkageError" "Long" "java.lang.Long"
          "Math" "java.lang.Math" "NegativeArraySizeException" "java.lang.NegativeArraySizeException"
          "NoClassDefFoundError" "java.lang.NoClassDefFoundError" "NoSuchFieldError" "java.lang.NoSuchFieldError"
          "NoSuchFieldException" "java.lang.NoSuchFieldException" "NoSuchMethodError" "java.lang.NoSuchMethodError"
          "NoSuchMethodException" "java.lang.NoSuchMethodException" "NullPointerException" "java.lang.NullPointerException"
          "Number" "java.lang.Number" "NumberFormatException" "java.lang.NumberFormatException"
          "Object" "java.lang.Object" "OutOfMemoryError" "java.lang.OutOfMemoryError"
          "Override" "java.lang.Override" "Package" "java.lang.Package"
          "Process" "java.lang.Process" "ProcessBuilder" "java.lang.ProcessBuilder"
          "Readable" "java.lang.Readable" "Runnable" "java.lang.Runnable"
          "Runtime" "java.lang.Runtime" "RuntimeException" "java.lang.RuntimeException"
          "RuntimePermission" "java.lang.RuntimePermission" "SecurityException" "java.lang.SecurityException"
          "SecurityManager" "java.lang.SecurityManager" "Short" "java.lang.Short"
          "StackOverflowError" "java.lang.StackOverflowError" "StackTraceElement" "java.lang.StackTraceElement"
          "StrictMath" "java.lang.StrictMath" "String" "java.lang.String"
          "StringBuffer" "java.lang.StringBuffer" "StringBuilder" "java.lang.StringBuilder"
          "StringIndexOutOfBoundsException" "java.lang.StringIndexOutOfBoundsException" "SuppressWarnings" "java.lang.SuppressWarnings"
          "System" "java.lang.System" "Thread" "java.lang.Thread"
          "Thread$State" "java.lang.Thread$State" "Thread$UncaughtExceptionHandler" "java.lang.Thread$UncaughtExceptionHandler"
          "ThreadDeath" "java.lang.ThreadDeath" "ThreadGroup" "java.lang.ThreadGroup"
          "ThreadLocal" "java.lang.ThreadLocal" "Throwable" "java.lang.Throwable"
          "TypeNotPresentException" "java.lang.TypeNotPresentException" "UnknownError" "java.lang.UnknownError"
          "UnsatisfiedLinkError" "java.lang.UnsatisfiedLinkError" "UnsupportedClassVersionError" "java.lang.UnsupportedClassVersionError"
          "UnsupportedOperationException" "java.lang.UnsupportedOperationException" "VerifyError" "java.lang.VerifyError"
          "VirtualMachineError" "java.lang.VirtualMachineError" "Void" "java.lang.Void"])))
