(ns clojure-elisp.package-header
  "Emacs library headers for a namespace that declares `:elisp/package` in its
   ns attr-map.

   (ns my.pkg
     \"One-line summary.

      Commentary paragraphs.\"
     {:elisp/package {:author  \"Jane Doe <jane@example.org>\"
                      :url     \"https://example.org/my-pkg\"
                      :version \"0.1.0\"
                      :package-requires [[emacs \"28.1\"]]
                      :keywords [\"convenience\"]
                      :license \"GPL-3.0-or-later\"}})

   The docstring's first line becomes the summary and the rest the Commentary
   section, unless `:commentary` is given. Package-Requires always names
   `emacs` and the runtime, the latter at `version/minimum-runtime-version`."
  (:require [clojure.string :as str]
            [clojure-elisp.version :as version]))

(def runtime-package
  "Package that provides the runtime every compiled file requires."
  'clojure-elisp-runtime)

(def default-emacs-version
  "Emacs version the runtime itself requires."
  "28.1")

(defn- version-parts [v]
  (mapv #(or (parse-long %) 0) (str/split (str v) #"\.")))

(defn- version< [a b]
  (let [pa (version-parts a)
        pb (version-parts b)
        n  (max (count pa) (count pb))
        pad #(into % (repeat (- n (count %)) 0))]
    (neg? (compare (pad pa) (pad pb)))))

(defn package-requires
  "Declared [[pkg \"version\"] ...] with emacs and the runtime added when absent.
   Throws when the runtime is declared older than compiled code needs."
  [declared]
  (let [pairs (mapv (fn [[p v]] [(symbol (name p)) (str v)]) declared)
        found (into {} pairs)
        rt    (get found runtime-package)]
    (when (and rt (version< rt version/minimum-runtime-version))
      (throw (ex-info (str "Package-Requires declares " runtime-package " " rt
                           ", but compiled code needs "
                           version/minimum-runtime-version)
                      {:declared rt :needs version/minimum-runtime-version})))
    (cond->> pairs
      (not (contains? found 'emacs))
      (into [['emacs default-emacs-version]])

      (not rt)
      (#(conj % [runtime-package version/minimum-runtime-version])))))

(defn- render-requires [pairs]
  (str "(" (str/join " " (map (fn [[p v]] (str "(" p " \"" v "\")")) pairs)) ")"))

(defn- dedent
  "Strip the indentation shared by all non-blank lines."
  [lines]
  (let [indents (->> lines
                     (remove str/blank?)
                     (map #(count (re-find #"^ *" %))))
        n       (if (seq indents) (apply min indents) 0)]
    (map #(if (str/blank? %) "" (subs % (min n (count %)))) lines)))

(defn split-doc
  "[summary commentary-lines] from an ns docstring."
  [doc]
  (let [[head & more] (str/split-lines (or doc ""))
        summary (-> (str/trim (or head "")) (str/replace #"\.$" ""))
        body    (->> (dedent more)
                     (drop-while str/blank?)
                     reverse
                     (drop-while str/blank?)
                     reverse)]
    [summary (vec body)]))

(defn- comment-lines [lines]
  (map #(if (str/blank? %) ";;" (str ";; " %)) lines))

(defn- people-lines [label people]
  (let [people (if (string? people) [people] people)
        pad    (apply str (repeat (+ 3 (count label)) \space))]
    (map-indexed (fn [i p] (if (zero? i) (str ";; " label ": " p) (str ";;" pad p)))
                 people)))

(defn render
  "Header text from the file name, ns docstring and :elisp/package map, up to and
   including the ;;; Code: line."
  [elisp-name doc {:keys [author maintainer url version keywords
                          license copyright commentary] :as pkg}]
  (let [[summary doc-body] (split-doc doc)
        commentary         (if commentary
                             (vec (dedent (str/split-lines commentary)))
                             doc-body)
        field              (fn [label v] (when v [(str ";; " label ": " v)]))]
    (str/join
     "\n"
     (concat
      [(str ";;; " elisp-name ".el --- " summary "  -*- lexical-binding: t; -*-")
       ""]
      (when copyright [(str ";; Copyright (C) " copyright) ""])
      (when author (people-lines "Author" author))
      (when maintainer (people-lines "Maintainer" maintainer))
      (field "URL" url)
      (field "Version" version)
      [(str ";; Package-Requires: " (render-requires (package-requires (:package-requires pkg))))]
      (when (seq keywords) [(str ";; Keywords: " (str/join ", " keywords))])
      (field "SPDX-License-Identifier" license)
      [""
       ";; This file is not part of GNU Emacs."
       ";; Generated by ClojureElisp: edit the .cljel source, not this file."
       ""
       ";;; Commentary:"
       ""]
      (comment-lines (if (seq commentary) commentary [summary]))
      [""
       ";;; Code:"
       ""]))))
