(ns clojure-elisp.examples-test
  "Tests for example files in examples/ directory."
  (:require [clojure.test :refer [deftest is testing]]
            [clojure-elisp.core :as clel]
            [clojure.string :as str]))

;; ============================================================================
;; hive-mcp-eca.cljel - Compilation Tests (clel-034)
;; ============================================================================

(deftest hive-mcp-eca-compiles-test
  (testing "hive-mcp-eca.cljel compiles without errors"
    (let [result (clel/compile-file-string (slurp "examples/hive-mcp-eca.cljel"))]
      (is (string? result) "Should produce string output")))

  (testing "defgroup is emitted correctly"
    (let [result (clel/compile-file-string (slurp "examples/hive-mcp-eca.cljel"))]
      (is (str/includes? result "defgroup hive-mcp-eca")
          "Should contain defgroup declaration")))

  (testing "defcustom is emitted correctly"
    (let [result (clel/compile-file-string (slurp "examples/hive-mcp-eca.cljel"))]
      (is (str/includes? result "defcustom hive-mcp-eca-auto-context")
          "Should contain defcustom for auto-context")))

  (testing "defvar for internal state is emitted"
    (let [result (clel/compile-file-string (slurp "examples/hive-mcp-eca.cljel"))]
      (is (str/includes? result "defvar hive-mcp-eca--initialized")
          "Should contain defvar for initialized state")))

  (testing "functions are emitted with namespace prefix"
    (let [result (clel/compile-file-string (slurp "examples/hive-mcp-eca.cljel"))]
      (is (str/includes? result "hive-mcp-eca-ensure-api")
          "Should contain ensure-api function")
      (is (str/includes? result "hive-mcp-eca-get-context")
          "Should contain get-context function")
      (is (str/includes? result "hive-mcp-eca-start-eca")
          "Should contain start-eca function")
      (is (str/includes? result "hive-mcp-eca-stop-eca")
          "Should contain stop-eca function")))

  (testing "interactive functions have (interactive) form"
    (let [result (clel/compile-file-string (slurp "examples/hive-mcp-eca.cljel"))]
      (is (str/includes? result "(interactive)")
          "Should contain interactive declaration")))

  (testing "provide form is at the end"
    (let [result (clel/compile-file-string (slurp "examples/hive-mcp-eca.cljel"))]
      ;; Compiler uses (provide 'name) format
      (is (str/includes? result "(provide 'hive-mcp-eca)")
          "Should provide the feature (auto-generated by compiler)")))

  (testing "parentheses are balanced"
    (let [result (clel/compile-file-string (slurp "examples/hive-mcp-eca.cljel"))
          opens (count (filter #(= % \() result))
          closes (count (filter #(= % \)) result))]
      (is (= opens closes)
          "Should have balanced parentheses"))))
