(ns clojure-elisp.package-header-test
  (:require [clojure.string :as str]
            [clojure.test :refer [deftest is testing]]
            [clojure-elisp.core :as clel]
            [clojure-elisp.package-header :as ph]
            [clojure-elisp.version :as version]))

(def packaged-src
  "(ns my.pkg
     \"Do a useful thing.

      Longer explanation,
        indented example.\"
     {:elisp/package {:author \"Jane Doe <jane@example.org>\"
                      :url \"https://example.org/my-pkg\"
                      :version \"0.1.0\"
                      :package-requires [[emacs \"29.1\"] [seq \"2.24\"]]
                      :keywords [\"convenience\" \"faces\"]
                      :license \"GPL-3.0-or-later\"}})
   (defn ok [] :ok)")

(deftest no-package-metadata-keeps-the-bare-header
  (let [out (clel/compile-file-string "(ns plain \"Doc.\")\n(defn ok [] :ok)")]
    (is (str/starts-with? out ";;; plain.el --- -*- lexical-binding: t; -*-\n;; Generated by ClojureElisp\n"))
    (is (not (str/includes? out "Package-Requires")))))

(deftest package-metadata-renders-library-headers
  (let [out (clel/compile-file-string packaged-src)]
    (testing "summary line from the docstring's first line, period dropped"
      (is (str/starts-with? out ";;; my-pkg.el --- Do a useful thing  -*- lexical-binding: t; -*-\n")))
    (testing "declared emacs kept, runtime appended at the minimum version"
      (is (str/includes? out (str ";; Package-Requires: ((emacs \"29.1\") (seq \"2.24\") (clojure-elisp-runtime \""
                                  version/minimum-runtime-version "\"))"))))
    (testing "fields"
      (is (str/includes? out ";; Author: Jane Doe <jane@example.org>\n"))
      (is (str/includes? out ";; Version: 0.1.0\n"))
      (is (str/includes? out ";; Keywords: convenience, faces\n"))
      (is (str/includes? out ";; SPDX-License-Identifier: GPL-3.0-or-later\n")))
    (testing "commentary from the docstring body, dedented"
      (is (str/includes? out ";;; Commentary:\n\n;; Longer explanation,\n;;   indented example.\n\n;;; Code:\n")))
    (testing "the runtime guard follows ;;; Code:"
      (is (< (str/index-of out ";;; Code:") (str/index-of out "(eval-and-compile"))))
    (testing "the body still compiles and the file still provides its feature"
      (is (str/includes? out "(defun my-pkg-ok ()"))
      (is (str/ends-with? out "(provide 'my-pkg)\n;;; my-pkg.el ends here\n")))))

(deftest package-requires-defaults
  (is (= [['emacs ph/default-emacs-version]
          [ph/runtime-package version/minimum-runtime-version]]
         (ph/package-requires nil)))
  (is (= [['emacs "30.1"] [ph/runtime-package "9.0.0"]]
         (ph/package-requires [['emacs "30.1"] ['clojure-elisp-runtime "9.0.0"]]))))

(deftest package-requires-refuses-a-runtime-older-than-emitted-code-needs
  (is (thrown-with-msg? clojure.lang.ExceptionInfo #"compiled code needs"
                        (ph/package-requires [['clojure-elisp-runtime "0.1"]]))))

(deftest multiple-authors-align-under-the-label
  (let [out (ph/render "x" "S." {:author ["A <a@x>" "B <b@x>"]})]
    (is (str/includes? out ";; Author: A <a@x>\n;;         B <b@x>\n"))))

(deftest explicit-commentary-wins-over-the-docstring-body
  (let [out (ph/render "x" "S.\n\n  Body." {:commentary "Custom."})]
    (is (str/includes? out ";;; Commentary:\n\n;; Custom.\n"))
    (is (not (str/includes? out "Body.")))))
