(ns clojure-elisp.package-header-test
  (:require [clojure.string :as str]
            [clojure.test :refer [deftest is testing]]
            [clojure-elisp.config :as config]
            [clojure-elisp.core :as clel]
            [clojure-elisp.fs-stub-test :refer [stub-fs]]
            [clojure-elisp.package-header :as ph]
            [clojure-elisp.project :as project]
            [clojure-elisp.version :as version]))

(def packaged-src
  "(ns my.pkg
     \"Do a useful thing.

      Longer explanation,
        indented example.\"
     {:elisp/package {:author \"Jane Doe <jane@example.org>\"
                      :url \"https://example.org/my-pkg\"
                      :version \"0.1.0\"
                      :package-requires [[emacs \"29.1\"] [seq \"2.24\"]]
                      :keywords [\"convenience\" \"faces\"]
                      :license \"GPL-3.0-or-later\"}})
   (defn ok [] :ok)")

(deftest no-package-metadata-keeps-the-bare-header
  (let [out (clel/compile-file-string "(ns plain \"Doc.\")\n(defn ok [] :ok)")]
    (is (str/starts-with? out ";;; plain.el --- -*- lexical-binding: t; -*-\n;; Generated by ClojureElisp\n"))
    (is (not (str/includes? out "Package-Requires")))))

(deftest package-metadata-renders-library-headers
  (let [out (clel/compile-file-string packaged-src)]
    (testing "summary line from the docstring's first line, period dropped"
      (is (str/starts-with? out ";;; my-pkg.el --- Do a useful thing  -*- lexical-binding: t; -*-\n")))
    (testing "declared emacs kept, runtime appended at the minimum version"
      (is (str/includes? out (str ";; Package-Requires: ((emacs \"29.1\") (seq \"2.24\") (clel \""
                                  version/minimum-runtime-version "\"))"))))
    (testing "fields"
      (is (str/includes? out ";; Author: Jane Doe <jane@example.org>\n"))
      (is (str/includes? out ";; Version: 0.1.0\n"))
      (is (str/includes? out ";; Keywords: convenience, faces\n"))
      (is (str/includes? out ";; SPDX-License-Identifier: GPL-3.0-or-later\n")))
    (testing "commentary from the docstring body, dedented"
      (is (str/includes? out ";;; Commentary:\n\n;; Longer explanation,\n;;   indented example.\n\n;;; Code:\n")))
    (testing "the runtime guard follows ;;; Code:"
      (is (< (str/index-of out ";;; Code:") (str/index-of out "(eval-and-compile"))))
    (testing "the body still compiles and the file still provides its feature"
      (is (str/includes? out "(defun my-pkg-ok ()"))
      (is (str/ends-with? out "(provide 'my-pkg)\n;;; my-pkg.el ends here\n")))))

(deftest package-requires-defaults
  (is (= [['emacs ph/default-emacs-version]
          [ph/runtime-package version/minimum-runtime-version]]
         (ph/package-requires nil)))
  (is (= [['emacs "30.1"] [ph/runtime-package "9.0.0"]]
         (ph/package-requires [['emacs "30.1"] ['clel "9.0.0"]]))))

(deftest package-requires-refuses-a-runtime-older-than-emitted-code-needs
  (is (thrown-with-msg? clojure.lang.ExceptionInfo #"compiled code needs"
                        (ph/package-requires [['clel "0.1"]]))))

(deftest multiple-authors-align-under-the-label
  (let [out (ph/render "x" "S." {:author ["A <a@x>" "B <b@x>"]})]
    (is (str/includes? out ";; Author: A <a@x>\n;;         B <b@x>\n"))))

(deftest assisted-by-lines-follow-the-author
  (testing "MELPA's CONTRIBUTING asks for the line right under Author"
    (is (str/includes? (ph/render "x" "S." {:author "A <a@x>" :assisted-by "Agent:model-1"})
                       ";; Author: A <a@x>\n;; Assisted-by: Agent:model-1\n")))
  (testing "one line per assistant, in secondary files too"
    (let [out (ph/render "x-y" "S." {:name "x" :author "A <a@x>"
                                     :assisted-by ["One:m1" "Two:m2"]})]
      (is (str/includes? out ";; Assisted-by: One:m1\n;; Assisted-by: Two:m2\n"))))
  (testing "absent unless declared"
    (is (not (str/includes? (ph/render "x" "S." {:author "A <a@x>"}) "Assisted-by")))))

(deftest explicit-commentary-wins-over-the-docstring-body
  (let [out (ph/render "x" "S.\n\n  Body." {:commentary "Custom."})]
    (is (str/includes? out ";;; Commentary:\n\n;; Custom.\n"))
    (is (not (str/includes? out "Body.")))))

;; ============================================================================
;; Every file of a package
;; ============================================================================

(def ^:private project-package
  "clel.edn :package: the package stated once for all its files."
  {:author   "Jane Doe <jane@example.org>"
   :url      "https://example.org/tod"
   :version  "0.2.0"
   :package-requires [['emacs "29.1"]]
   :keywords ["faces"]
   :license  "GPL-3.0-or-later"})

(def ^:private project-sources
  {"/src/tod.cljel"      "(ns tod \"Themes that follow the sun.\n\n   Main commentary.\"\n  (:require [tod.sun :as sun]))\n(defn f [] (sun/g))"
   "/src/tod/sun.cljel"  "(ns tod.sun \"Solar phase computation.\n\n   Sun commentary.\")\n(defn g [] 1)"
   "/src/tod/util.cljel" "(ns tod.util \"Small helpers.\")\n(defn h [] 2)"})

(defn- build
  "Compile the sources in store through the stub fs: {file-name elisp}."
  [store opts]
  (project/compile-project (stub-fs store) ["/src"] "/out" opts)
  (into {}
        (keep (fn [[path content]]
                (when (and (str/starts-with? path "/out/") (str/ends-with? path ".el"))
                  [(subs path 5) content])))
        @store))

(defn- header [el] (subs el 0 (str/index-of el ";;; Code:")))

(deftest project-package-gives-every-file-a-header
  (let [out  (build (atom project-sources) {:package project-package})
        main (out "tod.el")
        sun  (out "tod-sun.el")]
    (testing "the main file, named after the package, gets the full header"
      (is (str/starts-with? main ";;; tod.el --- Themes that follow the sun  -*- lexical-binding: t; -*-\n"))
      (is (str/includes? main ";; Version: 0.2.0\n"))
      (is (str/includes? main ";; URL: https://example.org/tod\n"))
      (is (str/includes? main (str ";; Package-Requires: ((emacs \"29.1\") (clel \""
                                   version/minimum-runtime-version "\"))\n")))
      (is (str/includes? main ";;; Commentary:\n\n;; Main commentary.\n")))
    (testing "a secondary file: summary, author, SPDX, Commentary, then Code"
      (is (str/starts-with? sun ";;; tod-sun.el --- Solar phase computation  -*- lexical-binding: t; -*-\n"))
      (is (str/includes? sun ";; Author: Jane Doe <jane@example.org>\n"))
      (is (str/includes? sun ";; SPDX-License-Identifier: GPL-3.0-or-later\n"))
      (is (str/includes? sun ";;; Commentary:\n\n;; Sun commentary.\n\n;;; Code:\n")))
    (testing "package-lint errors on Package-Requires outside the main file"
      (doseq [f ["tod-sun.el" "tod-util.el"]]
        (is (not (str/includes? (out f) "Package-Requires")) f)
        (is (not (str/includes? (out f) ";; Version:")) f)))
    (testing "the runtime guard follows ;;; Code: in every file"
      (doseq [[f el] out]
        (is (< (str/index-of el ";;; Code:") (str/index-of el "(eval-and-compile")) f)))
    (testing "a docstring without a body falls back to the summary as Commentary"
      (is (str/includes? (out "tod-util.el") ";;; Commentary:\n\n;; Small helpers\n")))))

(deftest one-namespace-declaring-the-package-covers-its-siblings
  (let [sources (update project-sources "/src/tod.cljel"
                        str/replace "(:require" (str (pr-str {:elisp/package project-package}) "\n  (:require"))
        out     (build (atom sources) nil)]
    (is (str/includes? (out "tod.el") "Package-Requires"))
    (is (str/starts-with? (out "tod-sun.el") ";;; tod-sun.el --- Solar phase computation"))
    (is (str/includes? (header (out "tod-sun.el")) ";; SPDX-License-Identifier: GPL-3.0-or-later"))
    (is (not (str/includes? (out "tod-sun.el") "Package-Requires")))))

(deftest a-project-without-a-package-compiles-as-before
  (let [out (build (atom project-sources) nil)]
    (doseq [src (vals project-sources)
            :let [f (clel/ns-derived-output-name src)]]
      (is (= (clel/compile-file-string src) (out f)) f)
      (is (str/includes? (out f) ";; Generated by ClojureElisp\n") f))))

(deftest a-file-named-outside-the-package-is-not-a-member
  (let [out (build (atom (assoc project-sources "/src/other.cljel" "(ns other \"Other.\")\n(defn o [] 3)"))
                   {:package project-package})]
    (is (not (str/includes? (out "other.el") "SPDX")))
    (is (str/includes? (out "other.el") ";; Generated by ClojureElisp\n"))))

(deftest package-name-selection
  (testing "the project's :name wins"
    (is (= "tod" (ph/package-name {:name 'tod} {"tod" nil "tod-sun" nil}))))
  (testing "else a file whose own map carries :package-requires"
    (is (= "tod" (ph/package-name nil {"tod" {:package-requires [['emacs "29.1"]]}
                                       "tod-sun" {:author "x"}}))))
  (testing "else the shortest name"
    (is (= "tod" (ph/package-name {} {"tod-sun" nil "tod" nil "tod-util" nil}))))
  (testing "no package anywhere"
    (is (nil? (ph/package-name nil {"tod" nil "tod-sun" nil})))))

(deftest file-commentary-stays-with-its-file
  (let [pkgs (ph/project-packages {:license "MIT"}
                                  {"tod" {:commentary "Main only." :version "1.0"}
                                   "tod-sun" nil})]
    (is (= "Main only." (get-in pkgs ["tod" :commentary])))
    (is (nil? (get-in pkgs ["tod-sun" :commentary])))
    (is (= "1.0" (get-in pkgs ["tod-sun" :version])) "package-wide keys reach every file")
    (is (= "tod" (get-in pkgs ["tod-sun" :name])))))

(deftest a-single-file-names-its-package-to-be-a-secondary-file
  (let [out (clel/compile-file-string
             "(ns tod.sun \"Solar.\" {:elisp/package {:name \"tod\" :license \"MIT\"}})")]
    (is (str/includes? out ";; SPDX-License-Identifier: MIT"))
    (is (not (str/includes? out "Package-Requires")))))

(deftest changing-the-project-package-recompiles-unchanged-sources
  (testing "the package map is a header input outside the source, so the
            incremental cache must see it change"
    (let [store (atom project-sources)
          _     (build store {:package project-package})
          out   (build store {:package (assoc project-package :version "0.3.0")})]
      (is (str/includes? (out "tod.el") ";; Version: 0.3.0")))))

(deftest clel-edn-package-is-validated-and-passed-on
  (let [store (atom (assoc project-sources
                           "/proj/clel.edn" (pr-str {:source-paths ["/src"] :output-dir "/out"
                                                     :package project-package})))]
    (is (= project-package (:package (config/read-project-config (stub-fs store) "/proj/clel.edn"))))
    (swap! store assoc "/proj/bad.edn" (pr-str {:package {:version 2}}))
    (is (thrown-with-msg? clojure.lang.ExceptionInfo #"Invalid clel.edn"
                          (config/read-project-config (stub-fs store) "/proj/bad.edn")))))
